apiVersion: v1
data:
  alertingServiceUserPassword: SElMTlZDVkZUaGdMdHVBYw==
  assistantServiceUserPassword: QU9XUEpqdXNxbVJBTUxqRg==
  authServiceUserPassword: akl1QVZOTkRqZkVsZ2tMSw==
  complianceServiceUserPassword: Wk1LTk9FcWVxQVRha1BtcQ==
  coreServiceUserPassword: cVFPaklkUnR4YU1Ta0lUag==
  dexServiceUserPassword: WUZHeUx4aWtJTVJTVG1oSw==
  informationUserPassword: Rml1cnFGRG13VGlMWE9XbA==
  integrationServiceUserPassword: blBZeHpzRXNBZmtVQUFxTg==
  migratorServiceUserPassword: TVVnYW5DdkpYZWtUenBEag==
  policyServiceUserPassword: SERjQnJ5REFGdGd5YlNzZQ==
  postgres-password: emNMcklCZXR1RUlzWGxMdg==
  postgresExporterUserPassword: dXJXY3dza1RISVVFS1hZTw==
  replication-password: WkhKdHZWZlpGUmFCdkZxaQ==
  reporterServiceUserPassword: QWlnQmNFY2JrWnVCVkxCQQ==
  schedulerUserPassword: T2Vvem5DUkp2bW5RWmloVg==
  steampipeUserPassword: QnBVZnNDTWNPUEluZWRmZA==
  subscriptionUserPassword: cG1CaGhtUVNSQW1sdkRmQg==
  taskServiceUserPassword: RHBJcEZxckFtV1paTm1icA==
  workspaceServiceUserPassword: QlZDdGhVSUxXTG5tb2Jydg==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: opensecurity
    meta.helm.sh/release-namespace: opensecurity
  creationTimestamp: "2025-04-28T18:46:19Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: postgres-secret
  namespace: opensecurity
  resourceVersion: "1125"
  uid: c7e3711f-2e44-4136-9e44-dca3d749705a
type: Opaque
